default_agent: troy
agents:
  troy:
    name: troy
    language: python
    node_version: '20'
    entrypoint: D:/support/customer-service-support-agent/starter/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: D:\support\customer-service-support-agent\starter
    aws:
      execution_role: arn:aws:iam::749016358464:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-b0b5f54b20
      execution_role_auto_create: false
      account: '749016358464'
      region: us-east-1
      ecr_repository: 749016358464.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-troy
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: troy-QFBQZ5CBOk
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:749016358464:runtime/troy-QFBQZ5CBOk
      agent_session_id: 0160601d-285d-48f9-a1c9-5b0197dca42e
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_AND_LTM
      memory_id: CustomerSupportMemory-aC6PFp8xLZ
      memory_arn: null
      memory_name: troy_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  Troy:
    name: Troy
    language: python
    node_version: '20'
    entrypoint: D:/support/customer-service-support-agent/starter/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: D:\support\customer-service-support-agent\starter
    aws:
      execution_role: arn:aws:iam::749016358464:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-5a99c57b24
      execution_role_auto_create: false
      account: '749016358464'
      region: us-east-1
      ecr_repository: 749016358464.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-troy
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_AND_LTM
      memory_id: CustomerSupportMemory-aC6PFp8xLZ
      memory_arn: null
      memory_name: Troy_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
